server:
  port: 8761

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8769

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    #防止自己注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
