server:
  port: 8761

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8769

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
