server:
  port: 8762
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    resource:
      #获取当前Token的用户信息
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      client-id: user-service
      client-secret: 123456
      #获取Token
      access-token-uri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server